#ifndef __std_msgs_msg_Header__
#define __std_msgs_msg_Header__

#include "Time.idl"

module std_msgs
{
  module msg
  { 
    struct Header
    { 
      std_msgs::msg::Time stamp; 
      string frame_id; 
    }; 
  }; 
};

#endif /* __std_msgs_msg_Header__ */
